server:
  port: 8081

cfrpc:
  zkServer: localhost:2181
  zkRoot: cfrpc
  # protocol: http，netty模式使用
  protocol: netty
  #  netty模式使用，http 方式无需配置netty.port
  netty:
    port: 8090

app:
  id: app1
  namespace: public
  env: dev
  metas: "{dc: 'bj', gray: 'false', unit: 'B001', version: '1.0.0'}"

logging:
  level:
    root: error
    com.bigwillc: warn
