server:
  port: 8081

cfrpc:
  service: http://localhost:8081, http://localhost:8082
  zkServer: localhost:2181
  zkRoot: cfrpc
  protocol: http
  netty:
    port: 8090

app:
  id: app1
  namespace: public
  env: dev
  metas: "{dc: 'bj', gray: 'false', unit: 'B001', version: '1.0.0'}"

logging:
  level:
    root: info
    com.bigwillc: debug
