server:
  port: 8080

cfrpc:
  services: http://localhost:8081, http://localhost:8082
  zkServer: localhost:2181
  zkRoot: cfrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 1
  timeout: 1000
  grayRatio: 10 # 0-100

logging:
  level:
    root: INFO
    com.bigwillc: debug
