server:
  port: 8080

cfrpc:
  zkServer: localhost:2181
  zkRoot: cfrpc
  # protocol: http, netty
  protocol: netty

app:
  id: app1
  namespace: public
  env: dev
  retries: 1
  timeout: 1000
  grayRatio: 10 # 0-100

logging:
  level:
    root: error
    com.bigwillc: warn
